export const questions = [
  {
    id: 'purpose',
    message: "Alright. One sentence — what does this do?\nNot the tech, not the features. The thing it actually does for the person using it.",
    type: 'text',
    placeholder: 'e.g. A tool that helps freelancers track client payments',
    required: true,
  },
  {
    id: 'users',
    message: "Who are the people using this?\nBe specific — the more you tell me, the better I can help.",
    type: 'text',
    placeholder: 'e.g. Freelance designers and developers',
    required: true,
  },
  {
    id: 'platform',
    message: 'Where does this live?',
    type: 'select',
    options: [
      { value: 'web', label: 'Web app', hint: 'runs in the browser' },
      { value: 'mobile', label: 'Mobile app', hint: 'iOS and/or Android' },
      { value: 'desktop', label: 'Desktop app', hint: 'Mac, Windows, Linux' },
      { value: 'api', label: 'API only', hint: 'no frontend' },
      { value: 'marketing', label: 'Marketing site', hint: 'content, no auth' },
      { value: 'both', label: 'Web + Mobile', hint: 'full product' },
    ],
    required: true,
  },
  {
    id: 'auth',
    message: 'Do users need accounts?',
    type: 'select',
    options: [
      { value: 'yes', label: 'Yes — users sign up and log in' },
      { value: 'no', label: 'No — no accounts needed' },
      { value: 'unsure', label: 'Not sure yet' },
    ],
    required: true,
  },
  {
    id: 'frontend_framework',
    message: 'What frontend framework are you using?',
    type: 'select',
    when: (answers) => answers.platform === 'web' || answers.platform === 'both' || answers.platform === 'marketing',
    options: [
      { value: 'nextjs', label: 'Next.js', hint: 'React, full stack' },
      { value: 'remix', label: 'Remix', hint: 'React, data-heavy' },
      { value: 'nuxt', label: 'Nuxt', hint: 'Vue, full stack' },
      { value: 'sveltekit', label: 'SvelteKit', hint: 'Svelte, full stack' },
      { value: 'astro', label: 'Astro', hint: 'content-first, minimal JS' },
      { value: 'angular', label: 'Angular', hint: 'opinionated, enterprise-ready' },
      { value: 'vue', label: 'Vue + Vite', hint: 'Vue SPA' },
      { value: 'react', label: 'React + Vite', hint: 'React SPA' },
      { value: 'vanilla', label: 'Vanilla JS', hint: 'no framework' },
      { value: 'html', label: 'HTML + CSS only', hint: 'static, no JS' },
      { value: 'other', label: 'Other', hint: 'tell me in constraints' },
      { value: 'unsure', label: 'Not sure yet', hint: 'I\'ll recommend' },
    ],
    required: false,
  },
  {
    id: 'mobile_framework',
    message: 'What framework for mobile?',
    type: 'select',
    when: (answers) => answers.platform === 'mobile' || answers.platform === 'both',
    options: [
      { value: 'expo', label: 'Expo', hint: 'React Native, managed workflow' },
      { value: 'rncli', label: 'React Native CLI', hint: 'more control, more setup' },
      { value: 'flutter', label: 'Flutter', hint: 'Dart, iOS + Android + Web' },
      { value: 'ionic', label: 'Ionic', hint: 'web-based, hybrid' },
      { value: 'other', label: 'Other', hint: 'tell me in constraints' },
      { value: 'unsure', label: 'Not sure yet', hint: 'I\'ll recommend' },
    ],
    required: false,
  },
  {
    id: 'backend',
    message: 'Does this need a backend or server?',
    type: 'select',
    options: [
      { value: 'yes', label: 'Yes — I need server-side logic or an API' },
      { value: 'no', label: 'No — frontend only' },
      { value: 'unsure', label: 'Not sure yet' },
    ],
    required: true,
  },
  {
    id: 'backend_language',
    message: 'What language or runtime for the backend?',
    type: 'select',
    when: (answers) => answers.backend === 'yes',
    options: [
      { value: 'node_express', label: 'Node.js + Express', hint: 'JavaScript, battle-tested' },
      { value: 'node_fastify', label: 'Node.js + Fastify', hint: 'JavaScript, high performance' },
      { value: 'node_hono', label: 'Node.js + Hono', hint: 'JavaScript, edge-ready' },
      { value: 'python_django', label: 'Python + Django', hint: 'batteries included, ORM built in' },
      { value: 'python_fastapi', label: 'Python + FastAPI', hint: 'async, great for APIs' },
      { value: 'python_flask', label: 'Python + Flask', hint: 'minimal, flexible' },
      { value: 'ruby_rails', label: 'Ruby on Rails', hint: 'convention over configuration' },
      { value: 'java_spring', label: 'Java + Spring Boot', hint: 'enterprise, object-oriented' },
      { value: 'csharp_dotnet', label: 'C# + .NET', hint: 'Microsoft ecosystem, enterprise' },
      { value: 'go_gin', label: 'Go + Gin', hint: 'fast, lightweight' },
      { value: 'go_echo', label: 'Go + Echo', hint: 'fast, minimal' },
      { value: 'rust_axum', label: 'Rust + Axum', hint: 'performance critical' },
      { value: 'php_laravel', label: 'PHP + Laravel', hint: 'popular, full featured' },
      { value: 'other', label: 'Other', hint: 'tell me in constraints' },
      { value: 'unsure', label: 'Not sure yet', hint: 'I\'ll recommend' },
    ],
    required: false,
  },
  {
    id: 'oop',
    message: 'Do you need object-oriented patterns?\nClasses, inheritance, design patterns.',
    type: 'select',
    when: (answers) => answers.backend === 'yes',
    options: [
      { value: 'yes', label: 'Yes — I work in OOP', hint: 'classes, inheritance, patterns' },
      { value: 'no', label: 'No — functional or procedural is fine' },
      { value: 'unsure', label: 'Not sure yet' },
    ],
    required: false,
  },
  {
    id: 'database',
    message: 'Does this need a database?',
    type: 'select',
    options: [
      { value: 'yes_new', label: 'Yes — starting fresh, no existing database' },
      { value: 'yes_existing', label: 'Yes — I already have a database' },
      { value: 'no', label: 'No — no data persistence needed' },
      { value: 'unsure', label: 'Not sure yet' },
    ],
    required: true,
  },
  {
    id: 'database_existing',
    message: 'Tell me about your existing database.',
    type: 'text',
    when: (answers) => answers.database === 'yes_existing',
    placeholder: 'e.g. PostgreSQL on AWS RDS, MongoDB Atlas, MySQL on PlanetScale',
    required: false,
  },
  {
    id: 'database_type',
    message: 'What kind of data are you storing?',
    type: 'select',
    when: (answers) => answers.database === 'yes_new',
    options: [
      { value: 'relational', label: 'Relational', hint: 'tables, rows, joins — Postgres, MySQL, SQLite' },
      { value: 'document', label: 'Document', hint: 'flexible JSON — MongoDB, Firestore' },
      { value: 'keyvalue', label: 'Key/value', hint: 'simple lookups — Redis, DynamoDB' },
      { value: 'unsure', label: 'Not sure yet', hint: 'I\'ll recommend based on your project' },
    ],
    required: false,
  },
  {
    id: 'orm',
    message: 'Do you need an ORM or query builder?',
    type: 'select',
    when: (answers) => answers.database === 'yes_new' || answers.database === 'yes_existing',
    options: [
      { value: 'yes', label: 'Yes', hint: 'Prisma, Drizzle, SQLAlchemy, Hibernate, ActiveRecord' },
      { value: 'no', label: 'No — I\'ll write raw SQL or queries' },
      { value: 'builtin', label: 'Built into my framework', hint: 'Django ORM, Rails ActiveRecord, .NET Entity' },
      { value: 'unsure', label: 'Not sure yet' },
    ],
    required: false,
  },
  {
    id: 'file_storage',
    message: 'Does this need to store files or media?\nImages, documents, videos, uploads.',
    type: 'select',
    options: [
      { value: 'yes', label: 'Yes' },
      { value: 'no', label: 'No' },
      { value: 'unsure', label: 'Not sure yet' },
    ],
    required: true,
  },
  {
    id: 'payments',
    message: 'Does this handle money?',
    type: 'select',
    options: [
      { value: 'yes_charge', label: 'Yes — charging users or subscriptions' },
      { value: 'yes_track', label: 'Yes — tracking expenses or balances only' },
      { value: 'no', label: 'No' },
      { value: 'later', label: 'Not for MVP' },
    ],
    required: true,
  },
  {
    id: 'content',
    message: 'Does this need a CMS?\nNon-developers editing content, blog posts, landing pages.',
    type: 'select',
    options: [
      { value: 'yes', label: 'Yes — non-devs need to edit content' },
      { value: 'no', label: 'No — content lives in code' },
      { value: 'unsure', label: 'Not sure yet' },
    ],
    required: true,
  },
  {
    id: 'realtime',
    message: 'Does anything need to update live?\nChat, notifications, live data feeds.',
    type: 'select',
    options: [
      { value: 'yes', label: 'Yes' },
      { value: 'no', label: 'No' },
      { value: 'unsure', label: 'Not sure yet' },
    ],
    required: true,
  },
  {
    id: 'offline',
    message: 'Does this need to work offline?',
    type: 'select',
    options: [
      { value: 'yes', label: 'Yes — core features must work without signal' },
      { value: 'no', label: 'No' },
      { value: 'unsure', label: 'Not sure yet' },
    ],
    required: true,
  },
  {
    id: 'timeline',
    message: "What's the timeline pressure?",
    type: 'select',
    options: [
      { value: 'asap', label: 'Ship fast — MVP in weeks' },
      { value: 'moderate', label: 'A few months — doing it right' },
      { value: 'relaxed', label: 'No rush — building carefully' },
      { value: 'unsure', label: 'Not sure yet' },
    ],
    required: true,
  },
  {
    id: 'constraints',
    message: "Any existing constraints I should know about?\nInfrastructure, locked dependencies, deployment targets, budget limits.",
    type: 'text',
    placeholder: 'e.g. Must deploy to AWS, already have a Postgres database (or press enter to skip)',
    required: false,
  },
];